### ISSUE TITLE
Merging cells

### ISSUE THREAD

**Issue by kamranpoladov** [gajus/table#187]
Is it possible to somehow merge cells with this library?

For example here two cells were merged into `0A`:

```
╔════╤════╤════╗
║    │ 0B │ 0C ║
╟ 0A ┼────┼────╢
║    │ 1B │ 1C ║
╟────┼────┼────╢
║ 2A │ 2B │ 2C ║
╚════╧════╧════╝
```

If not, would this feature be released in the nearest future or are there any workarounds for now? I am developing a CLI app where tables are used extensively and merging cells is empirical.

**Comment by nam-hle** [comment]
Hi @kamranpoladov, it's great to hear that the merging cell or column span feature is a quite useful one. It is also requested in the past at #12. The problem is we did not figure out the possible API for merging. 
If could, please describe your use case so we can kick off the feature as soon as possible.
