### ISSUE TITLE
Ability to progressively update a table

### ISSUE THREAD

**Issue by oncletom** [gajus/table#23]
Hi :-)

I have a case in which it takes time to retrieve all the data I need to display in a tabular way.
I was thinking of rendering the table progressively, as the data fetching progresses.

Do you think this is possible?

**Comment by gajus** [comment]
https://github.com/gajus/table#table-usage-streaming

**Comment by oncletom** [comment]
Hello :-)

Well if I understood correctly, the current streaming usage is only to *add* new lines isn't it?
I was rather thinking of having a predefined set of rows and columns which cells would be updated as I would *refresh* the cells value based.

If that's achievable via streaming, then I'm not sure to get how to write something else than just a *row* just by reading the documentation.

**Comment by gajus** [comment]
It is possible to achieve what you are describing. Refer to the implementation of the streaming mechanism.

It sounds like an interesting idea. However, it is not something thats implemented at the moment.

**Comment by oltodo** [comment]
Digging up this issue from the shadow because it's something that I'd have liked to do. For example, each rows are printing with a last column containing a status (e.g. processing) that could be change before printing next row.
It could be interesting to have a method called `clearRow()` (or something else) in `stream` object that could remove the last printed row and able us to rewrite it with new data.
